//====================================================================================================
// Base code generated with Velocity: SL Gen (Build 3.0.5898.28997)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by et.cheah at ENGTEONG on 11/30/2016 15:12:16 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ServiceModel;
using Ass5.Entities;
using MK.Framework.ACE.Entities;

namespace Ass5.Services.Contracts
{
    /// <summary>
    /// Service contract for TaskService.
    /// </summary>
    [ServiceContract]
    public interface ITaskService
    {
        [OperationContract]
        void Export();

        [OperationContract]
        Task GetTask(int taskID);

        [OperationContract]
        AccessPolicy GetUserPermission(long userID, string policyId);

        [OperationContract]
        List<Task> ListTask();

        [OperationContract]
        User LoginVerify(string Username, string Password);

        [OperationContract]
        void Update(Task task, TaskLog taskLog);

        [OperationContract]
        Task Apply(Task task);

        [OperationContract]
        void Approve(Task task);

        [OperationContract]
        void Cancel(Task task);

        //[OperationContract]
        //void Delay(Task task);

        [OperationContract]
        void Reject(Task task);

    }
}
