//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ass5.UI.Process.TaskWorkflowService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaskWorkflowService.ITaskWorkflowService")]
    public interface ITaskWorkflowService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWorkflowService/Apply", ReplyAction="http://tempuri.org/ITaskWorkflowService/ApplyResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ApplyResponseResult")]
        Ass5.Entities.Task Apply(Ass5.Entities.Task task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWorkflowService/Apply", ReplyAction="http://tempuri.org/ITaskWorkflowService/ApplyResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ApplyResponseResult")]
        System.Threading.Tasks.Task<Ass5.Entities.Task> ApplyAsync(Ass5.Entities.Task task);
        
        // CODEGEN: Generating message contract since the operation Approve is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWorkflowService/Approve", ReplyAction="http://tempuri.org/ITaskWorkflowService/ApproveResponse")]
        Ass5.UI.Process.TaskWorkflowService.ApproveResponse Approve(Ass5.UI.Process.TaskWorkflowService.ApproveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWorkflowService/Approve", ReplyAction="http://tempuri.org/ITaskWorkflowService/ApproveResponse")]
        System.Threading.Tasks.Task<Ass5.UI.Process.TaskWorkflowService.ApproveResponse> ApproveAsync(Ass5.UI.Process.TaskWorkflowService.ApproveRequest request);
        
        // CODEGEN: Generating message contract since the operation Reject is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWorkflowService/Reject", ReplyAction="http://tempuri.org/ITaskWorkflowService/RejectResponse")]
        Ass5.UI.Process.TaskWorkflowService.RejectResponse Reject(Ass5.UI.Process.TaskWorkflowService.RejectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWorkflowService/Reject", ReplyAction="http://tempuri.org/ITaskWorkflowService/RejectResponse")]
        System.Threading.Tasks.Task<Ass5.UI.Process.TaskWorkflowService.RejectResponse> RejectAsync(Ass5.UI.Process.TaskWorkflowService.RejectRequest request);
        
        // CODEGEN: Generating message contract since the operation Cancel is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWorkflowService/Cancel", ReplyAction="http://tempuri.org/ITaskWorkflowService/CancelResponse")]
        Ass5.UI.Process.TaskWorkflowService.CancelResponse Cancel(Ass5.UI.Process.TaskWorkflowService.CancelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWorkflowService/Cancel", ReplyAction="http://tempuri.org/ITaskWorkflowService/CancelResponse")]
        System.Threading.Tasks.Task<Ass5.UI.Process.TaskWorkflowService.CancelResponse> CancelAsync(Ass5.UI.Process.TaskWorkflowService.CancelRequest request);
        
        // CODEGEN: Generating message contract since the operation Update is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWorkflowService/Update", ReplyAction="http://tempuri.org/ITaskWorkflowService/UpdateResponse")]
        Ass5.UI.Process.TaskWorkflowService.UpdateResponse Update(Ass5.UI.Process.TaskWorkflowService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskWorkflowService/Update", ReplyAction="http://tempuri.org/ITaskWorkflowService/UpdateResponse")]
        System.Threading.Tasks.Task<Ass5.UI.Process.TaskWorkflowService.UpdateResponse> UpdateAsync(Ass5.UI.Process.TaskWorkflowService.UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Approve", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ApproveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Ass5.Entities.Task task;
        
        public ApproveRequest() {
        }
        
        public ApproveRequest(Ass5.Entities.Task task) {
            this.task = task;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApproveResponse {
        
        public ApproveResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Reject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RejectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Ass5.Entities.Task task;
        
        public RejectRequest() {
        }
        
        public RejectRequest(Ass5.Entities.Task task) {
            this.task = task;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RejectResponse {
        
        public RejectResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Cancel", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Ass5.Entities.Task task;
        
        public CancelRequest() {
        }
        
        public CancelRequest(Ass5.Entities.Task task) {
            this.task = task;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelResponse {
        
        public CancelResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Ass5.Entities.Task task;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Ass5.Entities.TaskLog taskLog;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(Ass5.Entities.Task task, Ass5.Entities.TaskLog taskLog) {
            this.task = task;
            this.taskLog = taskLog;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        public UpdateResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaskWorkflowServiceChannel : Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskWorkflowServiceClient : System.ServiceModel.ClientBase<Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService>, Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService {
        
        public TaskWorkflowServiceClient() {
        }
        
        public TaskWorkflowServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskWorkflowServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskWorkflowServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskWorkflowServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ass5.Entities.Task Apply(Ass5.Entities.Task task) {
            return base.Channel.Apply(task);
        }
        
        public System.Threading.Tasks.Task<Ass5.Entities.Task> ApplyAsync(Ass5.Entities.Task task) {
            return base.Channel.ApplyAsync(task);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ass5.UI.Process.TaskWorkflowService.ApproveResponse Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService.Approve(Ass5.UI.Process.TaskWorkflowService.ApproveRequest request) {
            return base.Channel.Approve(request);
        }
        
        public void Approve(Ass5.Entities.Task task) {
            Ass5.UI.Process.TaskWorkflowService.ApproveRequest inValue = new Ass5.UI.Process.TaskWorkflowService.ApproveRequest();
            inValue.task = task;
            Ass5.UI.Process.TaskWorkflowService.ApproveResponse retVal = ((Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService)(this)).Approve(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ass5.UI.Process.TaskWorkflowService.ApproveResponse> Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService.ApproveAsync(Ass5.UI.Process.TaskWorkflowService.ApproveRequest request) {
            return base.Channel.ApproveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ass5.UI.Process.TaskWorkflowService.ApproveResponse> ApproveAsync(Ass5.Entities.Task task) {
            Ass5.UI.Process.TaskWorkflowService.ApproveRequest inValue = new Ass5.UI.Process.TaskWorkflowService.ApproveRequest();
            inValue.task = task;
            return ((Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService)(this)).ApproveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ass5.UI.Process.TaskWorkflowService.RejectResponse Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService.Reject(Ass5.UI.Process.TaskWorkflowService.RejectRequest request) {
            return base.Channel.Reject(request);
        }
        
        public void Reject(Ass5.Entities.Task task) {
            Ass5.UI.Process.TaskWorkflowService.RejectRequest inValue = new Ass5.UI.Process.TaskWorkflowService.RejectRequest();
            inValue.task = task;
            Ass5.UI.Process.TaskWorkflowService.RejectResponse retVal = ((Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService)(this)).Reject(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ass5.UI.Process.TaskWorkflowService.RejectResponse> Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService.RejectAsync(Ass5.UI.Process.TaskWorkflowService.RejectRequest request) {
            return base.Channel.RejectAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ass5.UI.Process.TaskWorkflowService.RejectResponse> RejectAsync(Ass5.Entities.Task task) {
            Ass5.UI.Process.TaskWorkflowService.RejectRequest inValue = new Ass5.UI.Process.TaskWorkflowService.RejectRequest();
            inValue.task = task;
            return ((Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService)(this)).RejectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ass5.UI.Process.TaskWorkflowService.CancelResponse Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService.Cancel(Ass5.UI.Process.TaskWorkflowService.CancelRequest request) {
            return base.Channel.Cancel(request);
        }
        
        public void Cancel(Ass5.Entities.Task task) {
            Ass5.UI.Process.TaskWorkflowService.CancelRequest inValue = new Ass5.UI.Process.TaskWorkflowService.CancelRequest();
            inValue.task = task;
            Ass5.UI.Process.TaskWorkflowService.CancelResponse retVal = ((Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService)(this)).Cancel(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ass5.UI.Process.TaskWorkflowService.CancelResponse> Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService.CancelAsync(Ass5.UI.Process.TaskWorkflowService.CancelRequest request) {
            return base.Channel.CancelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ass5.UI.Process.TaskWorkflowService.CancelResponse> CancelAsync(Ass5.Entities.Task task) {
            Ass5.UI.Process.TaskWorkflowService.CancelRequest inValue = new Ass5.UI.Process.TaskWorkflowService.CancelRequest();
            inValue.task = task;
            return ((Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService)(this)).CancelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ass5.UI.Process.TaskWorkflowService.UpdateResponse Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService.Update(Ass5.UI.Process.TaskWorkflowService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(Ass5.Entities.Task task, Ass5.Entities.TaskLog taskLog) {
            Ass5.UI.Process.TaskWorkflowService.UpdateRequest inValue = new Ass5.UI.Process.TaskWorkflowService.UpdateRequest();
            inValue.task = task;
            inValue.taskLog = taskLog;
            Ass5.UI.Process.TaskWorkflowService.UpdateResponse retVal = ((Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ass5.UI.Process.TaskWorkflowService.UpdateResponse> Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService.UpdateAsync(Ass5.UI.Process.TaskWorkflowService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ass5.UI.Process.TaskWorkflowService.UpdateResponse> UpdateAsync(Ass5.Entities.Task task, Ass5.Entities.TaskLog taskLog) {
            Ass5.UI.Process.TaskWorkflowService.UpdateRequest inValue = new Ass5.UI.Process.TaskWorkflowService.UpdateRequest();
            inValue.task = task;
            inValue.taskLog = taskLog;
            return ((Ass5.UI.Process.TaskWorkflowService.ITaskWorkflowService)(this)).UpdateAsync(inValue);
        }
    }
}
