//====================================================================================================
// Base code generated with Vector: WFA Gen (Build 3.0.5898.28997)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by et.cheah at ENGTEONG on 11/30/2016 11:22:04 
//====================================================================================================

using System;
using System.Activities;
using System.Activities.Presentation.Metadata;
using System.ComponentModel;
using System.Windows;
using System.Collections.Generic;
using Ass5.Entities;
using Ass5.Workflows.Activities;

namespace Ass5.Workflows.Designers
{
    /// <summary>
    /// Designer class for Apply.
    /// </summary>
    public partial class ApplyDesigner : IRegisterMetadata
    {
        public ApplyDesigner()
        {
            InitializeComponent();
        }

        public void Register()
        {
            AttributeTableBuilder builder = new AttributeTableBuilder();

            builder.AddCustomAttributes(typeof(Apply), new Attribute[] {
            new DesignerAttribute(typeof(ApplyDesigner))});

            MetadataStore.AddAttributeTable(builder.CreateTable());
        }

        public void taskEntry_Loaded(object sender, RoutedEventArgs e)
        {
            taskEntry.ExpressionType = typeof(Task);
        }

        public void applyResultEntry_Loaded(object sender, RoutedEventArgs e)
        {
            applyResultEntry.ExpressionType = typeof(Task);
        }

    }
}

